#!/bin/bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
pushd $DIR > /dev/null

PATH=$DIR:$PATH 
if [[ -n "$ACCESS_EMAIL"  &&  -n "$ACCESS_PWD" ]]; then
   particle login $ACCESS_EMAIL $ACCESS_PWD
fi  


cucumber features --expand --tags ~@wip $*
popd
