#!/bin/bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
pushd $DIR > /dev/null

PATH=$DIR:$PATH 
if [[ -n "$ACCESS_EMAIL"  &&  -n "$ACCESS_PWD" ]]; then
   particle login --username $ACCESS_EMAIL --password $ACCESS_PWD
fi  

FILES=$*

if [ -z "$FILES" ]; then
   FILES=features
fi

cucumber --expand --tags ~@wip $FILES
result=$?
popd
exit $result
