name: Publish Package v2
on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
        description: 'The environment to publish to'
        default: 'staging'
      build_run_id:
        type: string
        required: true
        description: 'The build run id'
jobs:
    publish:
        runs-on: ubuntu-latest
        environment: ${{ inputs.environment }}
        steps:
            - uses: actions/checkout@v3

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: '16'
            - name: Configure NPM Token
              run: npm config set //registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}

            - name: Install dependencies
              run: npm install


            - name: Download workflow artifact
              uses: dawidd6/action-download-artifact@v3.1.4
              with:
                  run_id: ${{ inputs.build_run_id }}
                  name: package
                  path: build/

            - name: compress build with gz
              run: |
                cd build
                find . -type f ! -name "ParticleCLISetup.exe" -exec gzip "{}" +

            - name: generate manifest
              run: |
                npm run generate:manifest ./build ${{ secrets.BINARIES_BASE_URL }}

            - name: Upload artifacts
              uses: actions/upload-artifact@v2
              with:
                  name: release
                  path: build/
