name: Run Tests on Branch
on:
  push:
    branches:
      - 'feature/sc-126222/update-the-particle-cli-executable-in-workbench'
jobs:
  #call-tests:
  #  uses: ./.github/workflows/tests.yml
  #  secrets: inherit
  call-build:
    uses: ./.github/workflows/build.yml
    secrets: inherit
    #needs: call-tests
  call-publish:
    uses: ./.github/workflows/publish-v2.yml
    secrets: inherit
    needs: call-build
    with:
      environment: staging
      build_run_id: ${{ github.run_id }}
